manifest_version = 1

[module]
name = "BatterControl"
id = "batter_control"
description = "Manage Breadcord over the internet!"
version = "0.1.0"
license = "private"
authors = ["Brandon Qi (Sophon96)"]
requirements = ["quart~=0.18.4", "uvicorn[standard]~=0.23.2", "quart-auth~=0.9.0", "itsdangerous~=2.1.2"]
permissions = []